version: "3.7"

services:
  db:
    container_name: client
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=client
      - POSTGRES_PASSWORD=client
      - POSTGRES_DB=client

  api:
    image: golang:1.16-alpine
    volumes:
      - ./api:/app
    working_dir: /app
    command: go run .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - api/.env
